Induced changes.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -275,7 +275,7 @@ PACKAGE_BUGREPORT='edwards@jlab.org'
 ac_subdirs_all="$ac_subdirs_all other_libs/nml"
 ac_subdirs_all="$ac_subdirs_all other_libs/qio"
 ac_subdirs_all="$ac_subdirs_all other_libs/xpath_reader"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot ac_Nd ac_Nc ac_Ns PARALLEL_ARCH ac_sse ac_sse2 ARCHDEF_SUBSTITUTION QMP_CFLAGS QMP_LDFLAGS QMP_LIBS QMP_CONFIG CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE LIBXML2_CONFIG LIBXML2_CXXFLAGS LIBXML2_LIBS RANLIB ac_ct_RANLIB ARCH_SCALAR_TRUE ARCH_SCALAR_FALSE ARCH_PARSCALAR_TRUE ARCH_PARSCALAR_FALSE QDP_USE_SSE_TRUE QDP_USE_SSE_FALSE QDP_USE_SSE2_TRUE QDP_USE_SSE2_FALSE LATEX DVIPS DVIPDF DOXYGEN subdirs LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE ac_Nd ac_Nc ac_Ns PARALLEL_ARCH ac_sse ac_sse2 ARCHDEF_SUBSTITUTION QMP_CFLAGS QMP_LDFLAGS QMP_LIBS QMP_CONFIG CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE LIBXML2_CONFIG LIBXML2_CXXFLAGS LIBXML2_LIBS RANLIB ac_ct_RANLIB ARCH_SCALAR_TRUE ARCH_SCALAR_FALSE ARCH_PARSCALAR_TRUE ARCH_PARSCALAR_FALSE ARCH_SCALARVEC_TRUE ARCH_SCALARVEC_FALSE ARCH_PARSCALARVEC_TRUE ARCH_PARSCALARVEC_FALSE QDP_USE_SSE_TRUE QDP_USE_SSE_FALSE QDP_USE_SSE2_TRUE QDP_USE_SSE2_FALSE LATEX DVIPS DVIPDF DOXYGEN subdirs LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1501,15 +1501,6 @@ echo "${ECHO_T}no" >&6
   SET_MAKE="MAKE=${MAKE-make}"
 fi
 
-rm -rf .tst 2>/dev/null
-mkdir .tst 2>/dev/null
-if test -d .tst; then
-  am__leading_dot=.
-else
-  am__leading_dot=_
-fi
-rmdir .tst 2>/dev/null
-
  # test to see if srcdir already configured
 if test "`cd $srcdir && pwd`" != "`pwd`" &&
    test -f $srcdir/config.status; then
@@ -1529,8 +1520,8 @@ fi
 
 
 # Define the identity of the package.
- PACKAGE='qdp'
- VERSION='1.5'
+ PACKAGE=qdp
+ VERSION=1.5
 
 
 cat >>confdefs.h <<_ACEOF
@@ -1767,11 +1758,133 @@ echo "$as_me:  Scalar Build! Not checking for QMP " >&6;}
 
 
     ;;
+  scalarvec)
+    ARCHDEF_SUBSTITUTION=ARCH_SCALARVEC
+
+    { echo "$as_me:$LINENO:  Scalar with Vector extensions Build! Not checking for QMP " >&5
+echo "$as_me:  Scalar with Vector extensions Build! Not checking for QMP " >&6;}
+
+
+
+    ;;
   parscalar)
     ARCHDEF_SUBSTITUTION=ARCH_PARSCALAR
 
     { echo "$as_me:$LINENO:  Parscalar build! Checking for QMP " >&5
 echo "$as_me:  Parscalar build! Checking for QMP " >&6;}
+
+    if test "X${QMP_HOME}X" = "XX" ; then
+      # Extract the first word of "qmp-config", so it can be a program name with args.
+set dummy qmp-config; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_QMP_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $QMP_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_QMP_CONFIG="$QMP_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_QMP_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+QMP_CONFIG=$ac_cv_path_QMP_CONFIG
+
+if test -n "$QMP_CONFIG"; then
+  echo "$as_me:$LINENO: result: $QMP_CONFIG" >&5
+echo "${ECHO_T}$QMP_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+    else
+      # Extract the first word of "qmp-config", so it can be a program name with args.
+set dummy qmp-config; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_QMP_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $QMP_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_QMP_CONFIG="$QMP_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+as_dummy="${QMP_HOME}/bin:${PATH}"
+for as_dir in $as_dummy
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_QMP_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+QMP_CONFIG=$ac_cv_path_QMP_CONFIG
+
+if test -n "$QMP_CONFIG"; then
+  echo "$as_me:$LINENO: result: $QMP_CONFIG" >&5
+echo "${ECHO_T}$QMP_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+    fi
+
+    if test "X${QMP_CONFIG}X" != "XX" ; then
+      { echo "$as_me:$LINENO: Found QMP configuration program ${QMP_CONFIG}" >&5
+echo "$as_me: Found QMP configuration program ${QMP_CONFIG}" >&6;}
+      QMP_CFLAGS="`${QMP_CONFIG} --cflags`"
+
+      { echo "$as_me:$LINENO: QMP compile flags: ${QMP_CFLAGS}" >&5
+echo "$as_me: QMP compile flags: ${QMP_CFLAGS}" >&6;}
+      QMP_LDFLAGS="`${QMP_CONFIG} --ldflags`"
+
+      { echo "$as_me:$LINENO: QMP linking flags: ${QMP_LDFLAGS}" >&5
+echo "$as_me: QMP linking flags: ${QMP_LDFLAGS}" >&6;}
+      QMP_LIBS="`${QMP_CONFIG} --libs`"
+
+      { echo "$as_me:$LINENO: QMP libraries flags: ${QMP_LIBS}" >&5
+echo "$as_me: QMP libraries flags: ${QMP_LIBS}" >&6;}
+    else
+      { echo "$as_me:$LINENO: WARNING: QMP configuration program qmp-config not found." >&5
+echo "$as_me: WARNING: QMP configuration program qmp-config not found." >&2;}
+      { echo "$as_me:$LINENO: WARNING: Set environment variables QMP_CFLAGS QMP_LDFAGS QMP_LIBS
+        before configure" >&5
+echo "$as_me: WARNING: Set environment variables QMP_CFLAGS QMP_LDFAGS QMP_LIBS
+        before configure" >&2;}
+    fi
+    ;;
+  parscalarvec)
+    ARCHDEF_SUBSTITUTION=ARCH_PARSCALARVEC
+
+    { echo "$as_me:$LINENO:  Parscalar with Vector extensions build! Checking for QMP " >&5
+echo "$as_me:  Parscalar with Vector extensions build! Checking for QMP " >&6;}
 
     if test "X${QMP_HOME}X" = "XX" ; then
       # Extract the first word of "qmp-config", so it can be a program name with args.
@@ -1887,16 +2000,24 @@ echo "$as_me: error:  Unknown value for --enable-parallel-arch " >&2;}
     ;;
 esac
 
-DEPDIR="${am__leading_dot}deps"
+rm -f .deps 2>/dev/null
+mkdir .deps 2>/dev/null
+if test -d .deps; then
+  DEPDIR=.deps
+else
+  # MS-DOS does not allow filenames that begin with a dot.
+  DEPDIR=_deps
+fi
+rmdir .deps 2>/dev/null
+
 
           ac_config_commands="$ac_config_commands depfiles"
 
 
 am_make=${MAKE-make}
 cat > confinc << 'END'
-am__doit:
+doit:
 	@echo done
-.PHONY: am__doit
 END
 # If we don't find an include directive, just comment out the code.
 echo "$as_me:$LINENO: checking for style of include used by $am_make" >&5
@@ -2524,17 +2645,11 @@ else
     if depmode=$depmode \
        source=conftest.c object=conftest.o \
        depfile=conftest.Po tmpdepfile=conftest.TPo \
-       $SHELL ./depcomp $depcc -c -o conftest.o conftest.c \
-         >/dev/null 2>conftest.err &&
+       $SHELL ./depcomp $depcc -c -o conftest.o conftest.c >/dev/null 2>&1 &&
        grep conftest.h conftest.Po > /dev/null 2>&1 &&
        ${MAKE-make} -s -f confmf > /dev/null 2>&1; then
-      # icc doesn't choke on unknown options, it will just issue warnings
-      # (even with -Werror).  So we grep stderr for any message
-      # that says an option was ignored.
-      if grep 'ignoring option' conftest.err >/dev/null 2>&1; then :; else
-        am_cv_CXX_dependencies_compiler_type=$depmode
-        break
-      fi
+      am_cv_CXX_dependencies_compiler_type=$depmode
+      break
     fi
   done
 
@@ -2646,6 +2761,20 @@ echo "$as_me:$LINENO: checking if we can compile/link of a simple QMP C++ progra
 echo $ECHO_N "checking if we can compile/link of a simple QMP C++ program... $ECHO_C" >&6
 case ${PARALLEL_ARCH} in
   parscalar)
+    if test "X${qmp_link_ok}X" = "XyesX" ; then
+      echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    else
+      echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+      { { echo "$as_me:$LINENO: error: Cannot compile/link a basic QMP C++ program!
+        Check QMP_CFLAGS, QMP_LDFLAGS, QMP_LIBS." >&5
+echo "$as_me: error: Cannot compile/link a basic QMP C++ program!
+        Check QMP_CFLAGS, QMP_LDFLAGS, QMP_LIBS." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    ;;
+  parscalarvec)
     if test "X${qmp_link_ok}X" = "XyesX" ; then
       echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
@@ -3276,17 +3405,11 @@ else
     if depmode=$depmode \
        source=conftest.c object=conftest.o \
        depfile=conftest.Po tmpdepfile=conftest.TPo \
-       $SHELL ./depcomp $depcc -c -o conftest.o conftest.c \
-         >/dev/null 2>conftest.err &&
+       $SHELL ./depcomp $depcc -c -o conftest.o conftest.c >/dev/null 2>&1 &&
        grep conftest.h conftest.Po > /dev/null 2>&1 &&
        ${MAKE-make} -s -f confmf > /dev/null 2>&1; then
-      # icc doesn't choke on unknown options, it will just issue warnings
-      # (even with -Werror).  So we grep stderr for any message
-      # that says an option was ignored.
-      if grep 'ignoring option' conftest.err >/dev/null 2>&1; then :; else
-        am_cv_CXX_dependencies_compiler_type=$depmode
-        break
-      fi
+      am_cv_CXX_dependencies_compiler_type=$depmode
+      break
     fi
   done
 
@@ -3414,6 +3537,26 @@ if test "X${PARALLEL_ARCH}X" = "XparscalarX"; then
 else
   ARCH_PARSCALAR_TRUE='#'
   ARCH_PARSCALAR_FALSE=
+fi
+
+
+
+if test "X${PARALLEL_ARCH}X" = "XscalarvecX"; then
+  ARCH_SCALARVEC_TRUE=
+  ARCH_SCALARVEC_FALSE='#'
+else
+  ARCH_SCALARVEC_TRUE='#'
+  ARCH_SCALARVEC_FALSE=
+fi
+
+
+
+if test "X${PARALLEL_ARCH}X" = "XparscalarvecX"; then
+  ARCH_PARSCALARVEC_TRUE=
+  ARCH_PARSCALARVEC_FALSE='#'
+else
+  ARCH_PARSCALARVEC_TRUE='#'
+  ARCH_PARSCALARVEC_FALSE=
 fi
 
 
@@ -3789,6 +3932,20 @@ if test -z "${ARCH_PARSCALAR_TRUE}" && test -z "${ARCH_PARSCALAR_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"ARCH_PARSCALAR\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"ARCH_PARSCALAR\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ARCH_SCALARVEC_TRUE}" && test -z "${ARCH_SCALARVEC_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ARCH_SCALARVEC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ARCH_SCALARVEC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ARCH_PARSCALARVEC_TRUE}" && test -z "${ARCH_PARSCALARVEC_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ARCH_PARSCALARVEC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ARCH_PARSCALARVEC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -4356,7 +4513,6 @@ s,@ac_ct_STRIP@,$ac_ct_STRIP,;t t
 s,@INSTALL_STRIP_PROGRAM@,$INSTALL_STRIP_PROGRAM,;t t
 s,@AWK@,$AWK,;t t
 s,@SET_MAKE@,$SET_MAKE,;t t
-s,@am__leading_dot@,$am__leading_dot,;t t
 s,@ac_Nd@,$ac_Nd,;t t
 s,@ac_Nc@,$ac_Nc,;t t
 s,@ac_Ns@,$ac_Ns,;t t
@@ -4393,6 +4549,10 @@ s,@ARCH_SCALAR_TRUE@,$ARCH_SCALAR_TRUE,;t t
 s,@ARCH_SCALAR_FALSE@,$ARCH_SCALAR_FALSE,;t t
 s,@ARCH_PARSCALAR_TRUE@,$ARCH_PARSCALAR_TRUE,;t t
 s,@ARCH_PARSCALAR_FALSE@,$ARCH_PARSCALAR_FALSE,;t t
+s,@ARCH_SCALARVEC_TRUE@,$ARCH_SCALARVEC_TRUE,;t t
+s,@ARCH_SCALARVEC_FALSE@,$ARCH_SCALARVEC_FALSE,;t t
+s,@ARCH_PARSCALARVEC_TRUE@,$ARCH_PARSCALARVEC_TRUE,;t t
+s,@ARCH_PARSCALARVEC_FALSE@,$ARCH_PARSCALARVEC_FALSE,;t t
 s,@QDP_USE_SSE_TRUE@,$QDP_USE_SSE_TRUE,;t t
 s,@QDP_USE_SSE_FALSE@,$QDP_USE_SSE_FALSE,;t t
 s,@QDP_USE_SSE2_TRUE@,$QDP_USE_SSE2_TRUE,;t t
